"""added default start budget

Revision ID: 000001
Revises: 
Create Date: 2023-03-17 12:09:50.607243

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# fmt: off

# revision identifiers, used by Alembic.
revision = '000001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spaceaccess_groups', sa.Column('access_default_start_budget', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spaceaccess_groups', 'access_default_start_budget')
    # ### end Alembic commands ###
