"""add auto recharge dates

Revision ID: 000002
Revises: 000001
Create Date: 2023-03-26 13:20:51.481309

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# fmt: off

# revision identifiers, used by Alembic.
revision = '000002'
down_revision = '000001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spaceaccess_groups', sa.Column('access_last_group_recharge_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True))
    op.add_column('spaceaccess_properties', sa.Column('access_last_user_recharge_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spaceaccess_properties', 'access_last_user_recharge_at')
    op.drop_column('spaceaccess_groups', 'access_last_group_recharge_at')
    # ### end Alembic commands ###
