"""base

Revision ID: 000001
Revises: 
Create Date: 2023-02-19 15:10:22.868852

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "000001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invoice_consumption_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("consumed_as_guest", sa.Boolean(), nullable=True),
        sa.Column("linked_user_id", sa.Integer(), nullable=True),
        sa.Column("guest_is_member", sa.Boolean(), nullable=True),
        sa.Column("guest_email", sa.String(length=128), nullable=True),
        sa.Column("consumed_at", sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
        sa.Column("created_at", sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
        sa.Column("service_area", sa.String(length=128), nullable=True),
        sa.Column("service_name", sa.String(length=128), nullable=True),
        sa.Column("service_quantity", sa.Float(), nullable=True),
        sa.Column("service_unit", sa.String(length=128), nullable=True),
        sa.Column("project_name", sa.String(length=128), nullable=True),
        sa.Column("project_purpose", sa.String(length=128), nullable=True),
        sa.Column("project_details", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(["linked_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invoice_consumption_log_id"), "invoice_consumption_log", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_invoice_consumption_log_id"), table_name="invoice_consumption_log")
    op.drop_table("invoice_consumption_log")
    # ### end Alembic commands ###
