"""empty message

Revision ID: c6fcb9d9b352
Revises: d6685d9fb1af
Create Date: 2020-07-02 09:34:05.598755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6fcb9d9b352'
down_revision = 'd6685d9fb1af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actionlinks', sa.Column('need_login', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actionlinks', 'need_login')
    # ### end Alembic commands ###
