"""empty message

Revision ID: d6685d9fb1af
Revises:
Create Date: 2020-07-01 17:36:39.429983

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd6685d9fb1af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actionlinks', sa.Column('run_only_once', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actionlinks', 'run_only_once')
    # ### end Alembic commands ###
